# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 549d690613c6b813f5ac4ab055d81844ee48407f3b587bb274bd04120a838ccf4666f20ee257db0f41af1ac0c2ecdabdf3bbeb79a2473aab67f3b0751a363c16

test:
  secret_key_base: df634f5f04ae704da0802446120a5c7ff11173019b499c8a4d97e89ea2f594f584a420e7be5c854eadcaee1c9f48912949df09d0ddd72de8da129a211804b486

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
